-- CreateTable
CREATE TABLE "Txn" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Txn_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Txn" ADD CONSTRAINT "Txn_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
